model:
  _target_: src.modules.models.classification.ClassifierMultipleHead
  model_name: "torchvision.models/resnext50_32x4d"
  use_pretrained: True
  num_classes: [92, 4]
  freeze_params: null
  bias: True
  groups: 64

loss:
  _target_: "torch.nn.CrossEntropyLoss"

metrics:
  main:
    _target_: "src.modules.metrics.Accuracy"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
