model:
  _target_: src.modules.models.reindetification.ReIdentificator
  model_name: "torchvision.models/resnet18"
  use_pretrained: True
  embedding_size: 512
  proj_hidden_dim: 1536
  bias: True
  p: 3
  gem_trainable: False
  head_type: "fc" # 'gem'

loss:
  _target_: "src.modules.losses.AngularPenaltySMLoss"
  embedding_size: 512
  num_classes: 57457
  loss_type: "CosFace"

metrics:
  main:
    _target_: "src.modules.metrics.Accuracy"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
