_target_: src.datamodules.datamodules.MultipleDataModule

defaults:
  - _self_
  - loaders: loaders.yaml
  - transforms: transforms.yaml

datasets:
  label1:
    train:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/train/label1_data.json
      data_path: ${paths.data_dir}/train/label1_data.h5

    valid:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/valid/label1_data.json
      data_path: ${paths.data_dir}/valid/label1_data.h5

    test:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/test/label1_data.json
      data_path: ${paths.data_dir}/test/label1_data.h5

  label2:
    train:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/train/label2_data.json
      data_path: ${paths.data_dir}/train/label2_data.h5

    valid:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/valid/label2_data.json
      data_path: ${paths.data_dir}/valid/label2_data.h5

    test:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/test/label2_data.json
      data_path: ${paths.data_dir}/test/label2_data.h5
